import { prisma } from "@/lib/prisma";
import type { Permission } from "@/lib/permissions";

// Metadata-only registry backing the Permission Matrix UI's checkbox grid
// (src/app/admin/(shell)/permission-matrix/page.tsx) — NOT the authorization
// source of truth (that's ROLE_PERMISSIONS in src/lib/permissions.ts). Every
// permission string that exists gets a row here so it can be assigned to a
// custom role; descriptions are short, human-readable labels for the grid.
const DESCRIPTIONS: Partial<Record<Permission, string>> = {
  "profile:view": "View profile details",
  "profile:edit": "Edit profile information",
  "profile:delete": "Archive / soft-delete a profile",
  "profile:verify": "Mark a profile as verified",
  "profile:status": "Change a profile's status",
  "profile:archive": "Archive a profile",
  "profile:restore": "Restore an archived profile",
  "profile:assign": "Assign a profile to a staff member",
  "contact:reveal": "Reveal hidden contact information",
  "match:run": "Run and review the matching engine",
  "match:configure": "Change matching algorithm weights and thresholds",
  "proposal:create": "Create a rishta proposal",
  "proposal:edit": "Edit an existing proposal",
  "proposal:assign": "Assign a proposal to a staff member",
  "proposal:finalize": "Finalize a proposal",
  "proposal:archive": "Archive a proposal",
  "note:add": "Add a private admin note",
  "notes:view": "View admin notes on a record",
  "notes:edit": "Edit an admin note",
  "notes:delete": "Delete an admin note",
  "profiles:export": "Export profile data",
  "communication:add": "Log a manual communication",
  "communication:view": "View communication history",
  "communication:send": "Send a communication",
  "communication:message:view": "View full message bodies",
  "audit:view": "View the audit log",
  "settings:edit": "Change platform settings",
  "admin:manage": "Manage admin accounts and roles",
  "verification:view": "View verification status",
  "verification:review": "Review a verification case",
  "verification:approve": "Approve a verification decision",
  "verification:reject": "Reject a verification decision",
  "verification:reverify": "Request re-verification",
  "verification:request-info": "Request more information from a member for verification",
  "verification:document:view": "View uploaded verification documents",
  "verification:flag:manage": "Manage security/trust flags",
  "verification:duplicate:scan": "Run duplicate-profile scans",
  "verification:assign": "Assign a verification case to staff",
  "notification:template:manage": "Edit notification templates",
  "reports:view": "View reports and analytics",
  "reports:export": "Export a report",
  "reports:income:view": "View income analytics",
  "reports:staff-performance:view": "View staff performance analytics",
  "reports:schedule:manage": "Schedule automated reports",
  "sensitive:income:view": "View individual income figures",
  "sensitive:notes:view": "View other admins' private notes",
  "sensitive:family:view": "View family background details",
  "staff:view": "View the team workload dashboard",
  // ---------- Support, Complaints, Safety & Case Management (STEP 12) ----------
  "support:view": "View support-request cases",
  "support:create": "Create a support-request case",
  "support:edit": "Edit a support-request case",
  "support:assign": "Assign a support-request case",
  "support:manage": "Manage support-request cases",
  "support:resolve": "Resolve a support-request case",
  "support:close": "Close a support-request case",
  "cases:view": "View cases",
  "cases:create": "Create an internal case",
  "cases:edit": "Edit a case",
  "cases:assign": "Assign a case to staff",
  "cases:manage": "Manage cases",
  "cases:escalate": "Escalate a case",
  "cases:escalate:senior": "Escalate a case to senior admin level",
  "cases:staff-conduct:view": "View staff-conduct complaint cases",
  "cases:resolve": "Resolve a case",
  "cases:close": "Close a case",
  "cases:reopen": "Reopen a closed case",
  "cases:merge": "Merge duplicate cases",
  "complaints:view": "View complaint cases",
  "complaints:create": "Create a complaint case",
  "complaints:review": "Review a complaint case",
  "complaints:resolve": "Resolve a complaint case",
  "safety_cases:view": "View safety-report cases",
  "safety_cases:review": "Review a safety-report case",
  "safety_cases:escalate": "Escalate a safety-report case",
  "safety_cases:resolve": "Resolve a safety-report case",
  "sensitive:case:evidence:view": "View case evidence files",
  "sensitive:case:notes:view": "View case internal notes above your tier",
  "sensitive:case:restricted-profile:view": "View cases involving restricted profiles",
  "profile:restrict": "Apply a scoped restriction to a profile",
  "profile:suspend": "Suspend a profile",
  // ---------- Data Privacy, Consent, Account Management & Retention (STEP 13) ----------
  "privacy:view": "View the Privacy Center",
  "privacy:manage": "Manage privacy settings",
  "privacy:consent:view": "View a profile's consent history",
  "privacy:consent:manage": "Manage a profile's consent records",
  "privacy:requests:view": "View privacy requests",
  "privacy:requests:manage": "Manage and resolve privacy requests",
  "privacy:export:view": "View data export requests",
  "privacy:export:create": "Create a data export on a profile's behalf",
  "privacy:delete:manage": "Approve or reject account deletion requests",
  "privacy:retention:view": "View retention policies",
  "privacy:retention:manage": "Configure retention policies",
  "privacy:hold:view": "View legal/administrative holds",
  "privacy:hold:manage": "Place or lift a legal/administrative hold",
  "privacy:incidents:view": "View privacy incidents",
  "privacy:incidents:manage": "Manage privacy incidents",
  "privacy:break-glass:manage": "Grant emergency break-glass access",
  "contact:reveal:override": "Share contact info outside an approved proposal",
  "sensitive:contact:view": "View private contact information (mobile, WhatsApp, email)",
  "sensitive:documents:view": "View private verification/identity documents",
  "sensitive:photos:view": "View profile photos",
  "privacy_incidents:view": "View privacy-incident cases",
  "privacy_incidents:review": "Review a privacy-incident case",
  "privacy_incidents:resolve": "Resolve a privacy-incident case",
  // ---------- Payment, Subscription, Packages & Financial Management (STEP 14) ----------
  "finance:view": "View the Finance Center",
  "finance:dashboard:view": "View the financial dashboard",
  "finance:payments:view": "View payments",
  "finance:payments:manage": "Manage payments and manual payment verification",
  "finance:invoices:view": "View invoices",
  "finance:invoices:manage": "Manage invoices",
  "finance:refunds:view": "View refunds",
  "finance:refunds:request": "Request a refund",
  "finance:refunds:approve": "Approve a refund",
  "finance:subscriptions:view": "View subscriptions",
  "finance:subscriptions:manage": "Manage subscriptions",
  "finance:packages:view": "View packages and pricing",
  "finance:packages:manage": "Manage packages, pricing, and entitlements",
  "finance:coupons:view": "View coupons and discounts",
  "finance:coupons:manage": "Manage coupons and discounts",
  "finance:reconciliation:view": "View financial reconciliation",
  "finance:reconciliation:manage": "Run financial reconciliation",
  "finance:reports:view": "View financial reports",
  "finance:reports:export": "Export a financial report",
  "sensitive:finance:view": "View sensitive financial details",
  "sensitive:finance:export": "Export sensitive financial data",

  // ---------- Payment Rollout Phases (STEP 14 add-on) ----------
  "finance:rollout:view": "View payment rollout stage, feature flags, and health",
  "finance:rollout:manage": "Change payment feature flags and beta/internal eligibility config",
  "finance:rollout:enable": "Advance the payment rollout stage forward",
  "finance:rollout:disable": "Disable payments (kill switch) or roll back the rollout stage",
  "finance:provider:manage": "Change the active payment provider or environment config",
  "finance:webhooks:view": "View payment webhook health and delivery status",
  // ---------- Production, DevOps & Recovery (STEP 15) ----------
  "system:view": "View System Health and operational status",
  "system:config:manage": "Change monitoring thresholds, backup policy and system configuration",
  "system:flags:manage": "Toggle feature flags",
  "system:maintenance:manage": "Enable/disable maintenance mode and change the operational state",
  "system:emergency:manage": "Use the emergency kill switches",
  "system:backup:view": "View backup and recovery status",
  "system:backup:trigger": "Trigger a backup or restore verification",
  "system:restore:approve": "Request or approve a restore",
  "system:jobs:view": "View background jobs and scheduled tasks",
  "system:jobs:manage": "Retry, cancel or resolve background jobs; run the scheduled tick",
  "alerts:view": "View alerts and incidents",
  "alerts:manage": "Acknowledge, assign, resolve alerts and open incidents",
  "readiness:view": "View Production Readiness and release records",
  "releases:manage": "Approve releases and record rollbacks",
  "ai:view": "View the AI Matchmaking Assistant and its overview",
  "ai:use": "Use AI analysis (profile summary, match explanation, comparison, data quality) on profiles you can access",
  "ai:copilot": "Use the Admin Copilot (read-only questions within your own permissions)",
  "ai:communication:draft": "Ask the AI to DRAFT messages (sending stays a separate, confirmed action)",
  "ai:report:use": "Ask the AI to summarise reports you are already allowed to see",
  "ai:config:manage": "Change AI settings (provider, limits, privacy, storage, prompts)",
  "ai:rollout:manage": "Change the AI rollout phase",
  "ai:killswitch": "Use the AI kill switch",
  "ai:activity:view": "View the AI activity log (metadata only)",
  "ai:usage:view": "View AI usage and estimated cost",
  "ai:test:run": "Run the AI safety/privacy/security/regression test suites",
  // ---------- Exact Admin Roles & Granular Permission Matrix (STEP 17) ----------
  "roles:view": "View roles and their permissions",
  "roles:create": "Create a custom role",
  "roles:edit": "Edit a role's permissions",
  "roles:disable": "Disable a role",
  "roles:assign": "Assign a role to an admin",
  "roles:delete": "Delete a custom role",

  // ---------- Workflow & Task Management (STEP 18) ----------
  "tasks:view": "View the Workflow & Tasks module",
  "tasks:view:own": "View your own assigned tasks (My Work Queue)",
  "tasks:view:team": "View your team's tasks (Team Work Queue)",
  "tasks:view:all": "View every task on the platform (Global Work)",
  "tasks:create": "Create a task automatically or manually",
  "tasks:create:manual": "Manually create a task via 'Create Task'",
  "tasks:assign": "Assign an unassigned task to a staff member",
  "tasks:assign:any": "Assign a task across any department/domain",
  "tasks:reassign": "Reassign an already-assigned task",
  "tasks:accept": "Accept a task assigned to you",
  "tasks:complete": "Mark a task complete",
  "tasks:reopen": "Reopen a completed/cancelled task",
  "tasks:cancel": "Cancel a task",
  "tasks:escalate": "Escalate a task to the next level",
  "tasks:escalate:senior": "Escalate a task to the senior/final tier",
  "tasks:comment": "Comment on a task",
  "tasks:comment:internal": "Post an internal-only task comment",
  "tasks:attachments:upload": "Upload an attachment to a task",
  "tasks:attachments:view": "View a task's attachments",
  "tasks:bulk-actions": "Perform bulk actions on multiple tasks at once",
  "tasks:templates:manage": "Create and edit task templates",
  "tasks:sla:manage": "Configure SLA targets per task type",
  "tasks:automation:manage": "Configure workflow automation rules",
  "tasks:workflow-failures:view": "View the Workflow Failures (dead-letter) queue",
  "tasks:workflow-failures:resolve": "Retry or resolve a failed workflow event",
  "tasks:reports:view": "View Workflow Reports and analytics",
  "staff:availability:manage": "Configure staff availability and backup routing",
  "approvals:view": "View approval requests",
  "approvals:create": "Create a high-risk action approval request",
  "approvals:submit": "Submit a draft approval request for review",
  "approvals:approve": "Approve an approval request",
  "approvals:reject": "Reject an approval request",
  "approvals:request-changes": "Request changes on an approval request",
  "approvals:assign": "Assign a checker to an approval request",
  "approvals:delegate": "Delegate approval decisions to another admin",
  "approvals:escalate": "Escalate an approval request",
  "approvals:cancel": "Cancel an approval request",
  "approvals:execute": "Execute an approved high-risk action",
  "approvals:audit:view": "View the approval audit trail",
  "approvals:policy:view": "View approval governance policies",
  "approvals:policy:manage": "Configure approval governance policies",
  "approvals:emergency-override": "Use the emergency override for a high-risk action",
  "approvals:bulk:view": "View bulk approval requests",
  "approvals:bulk:approve": "Approve a bulk sensitive action",
  "sensitive:approval:view": "View approval requests involving sensitive data",
  "sensitive:approval:approve": "Approve a sensitive-data approval request",
  "sensitive:approval:execute": "Execute a sensitive-data approval request",
  "finance:approval:view": "View financial approval requests",
  "finance:approval:approve": "Approve a financial approval request",
  "finance:approval:execute": "Execute an approved financial action",
  "privacy:approval:view": "View privacy approval requests",
  "privacy:approval:approve": "Approve a privacy approval request",
  "privacy:approval:execute": "Execute an approved privacy action",
  "security:approval:view": "View security approval requests",
  "security:approval:approve": "Approve a security approval request",
  "security:approval:execute": "Execute an approved security action",
  "ai:approval:view": "View AI governance approval requests",
  "ai:approval:approve": "Approve an AI governance approval request",
  "ai:approval:execute": "Execute an approved AI governance action",
  "search:view": "Search and browse candidates",
  "search:advanced": "Use the advanced smart filter builder",
  "search:sensitive": "Filter candidate search by sensitive fields (e.g. income)",
  "search:export": "Export candidate search results",
  "search:saved:view": "View saved search presets",
  "search:saved:create": "Save a new search preset",
  "search:saved:edit": "Edit a shared search preset",
  "search:saved:delete": "Delete a search preset",
  "search:bulk": "Perform bulk actions on search results",
  "candidate:view": "View candidate discovery results",
  "candidate:compare": "Compare multiple candidates side by side",
  "candidate:shortlist": "Create and manage candidate shortlists",
  "candidate:recommend": "Run mutual-compatibility candidate search",
  "family:manage": "Search, review, suspend, and manage family/guardian accounts",
};

function moduleAndAction(key: Permission): { module: string; action: string } {
  const parts = key.split(":");
  return { module: parts[0], action: parts.slice(1).join(":") };
}

export async function ensurePermissionDefsSeeded(): Promise<void> {
  const keys = Object.keys(DESCRIPTIONS) as Permission[];
  await prisma.$transaction(
    keys.map((key) => {
      const { module, action } = moduleAndAction(key);
      return prisma.permissionDef.upsert({
        where: { key },
        update: { module, action, description: DESCRIPTIONS[key] ?? null },
        create: { key, module, action, description: DESCRIPTIONS[key] ?? null },
      });
    })
  );
}
