import { prisma } from "@/lib/prisma";
import type { Permission } from "@/lib/permissions";

// Metadata-only registry backing the Permission Matrix UI's checkbox grid
// (src/app/admin/(shell)/permission-matrix/page.tsx) — NOT the authorization
// source of truth (that's ROLE_PERMISSIONS in src/lib/permissions.ts). Every
// permission string that exists gets a row here so it can be assigned to a
// custom role; descriptions are short, human-readable labels for the grid.
const DESCRIPTIONS: Partial<Record<Permission, string>> = {
  "profile:view": "View profile details",
  "profile:edit": "Edit profile information",
  "profile:delete": "Archive / soft-delete a profile",
  "profile:verify": "Mark a profile as verified",
  "profile:status": "Change a profile's status",
  "profile:archive": "Archive a profile",
  "profile:restore": "Restore an archived profile",
  "profile:assign": "Assign a profile to a staff member",
  "contact:reveal": "Reveal hidden contact information",
  "match:run": "Run and review the matching engine",
  "match:configure": "Change matching algorithm weights and thresholds",
  "proposal:create": "Create a rishta proposal",
  "proposal:edit": "Edit an existing proposal",
  "proposal:assign": "Assign a proposal to a staff member",
  "proposal:finalize": "Finalize a proposal",
  "proposal:archive": "Archive a proposal",
  "note:add": "Add a private admin note",
  "notes:view": "View admin notes on a record",
  "notes:edit": "Edit an admin note",
  "notes:delete": "Delete an admin note",
  "profiles:export": "Export profile data",
  "communication:add": "Log a manual communication",
  "communication:view": "View communication history",
  "communication:send": "Send a communication",
  "communication:message:view": "View full message bodies",
  "audit:view": "View the audit log",
  "settings:edit": "Change platform settings",
  "admin:manage": "Manage admin accounts and roles",
  "verification:view": "View verification status",
  "verification:review": "Review a verification case",
  "verification:approve": "Approve a verification decision",
  "verification:reject": "Reject a verification decision",
  "verification:reverify": "Request re-verification",
  "verification:request-info": "Request more information from a member for verification",
  "verification:document:view": "View uploaded verification documents",
  "verification:flag:manage": "Manage security/trust flags",
  "verification:duplicate:scan": "Run duplicate-profile scans",
  "verification:assign": "Assign a verification case to staff",
  "notification:template:manage": "Edit notification templates",
  "reports:view": "View reports and analytics",
  "reports:export": "Export a report",
  "reports:income:view": "View income analytics",
  "reports:staff-performance:view": "View staff performance analytics",
  "reports:schedule:manage": "Schedule automated reports",
  "sensitive:income:view": "View individual income figures",
  "sensitive:notes:view": "View other admins' private notes",
  "sensitive:family:view": "View family background details",
  "staff:view": "View the team workload dashboard",
  // ---------- Support, Complaints, Safety & Case Management (STEP 12) ----------
  "support:view": "View support-request cases",
  "support:create": "Create a support-request case",
  "support:edit": "Edit a support-request case",
  "support:assign": "Assign a support-request case",
  "support:manage": "Manage support-request cases",
  "support:resolve": "Resolve a support-request case",
  "support:close": "Close a support-request case",
  "cases:view": "View cases",
  "cases:create": "Create an internal case",
  "cases:edit": "Edit a case",
  "cases:assign": "Assign a case to staff",
  "cases:manage": "Manage cases",
  "cases:escalate": "Escalate a case",
  "cases:escalate:senior": "Escalate a case to senior admin level",
  "cases:staff-conduct:view": "View staff-conduct complaint cases",
  "cases:resolve": "Resolve a case",
  "cases:close": "Close a case",
  "cases:reopen": "Reopen a closed case",
  "cases:merge": "Merge duplicate cases",
  "complaints:view": "View complaint cases",
  "complaints:create": "Create a complaint case",
  "complaints:review": "Review a complaint case",
  "complaints:resolve": "Resolve a complaint case",
  "safety_cases:view": "View safety-report cases",
  "safety_cases:review": "Review a safety-report case",
  "safety_cases:escalate": "Escalate a safety-report case",
  "safety_cases:resolve": "Resolve a safety-report case",
  "sensitive:case:evidence:view": "View case evidence files",
  "sensitive:case:notes:view": "View case internal notes above your tier",
  "sensitive:case:restricted-profile:view": "View cases involving restricted profiles",
  "profile:restrict": "Apply a scoped restriction to a profile",
  "profile:suspend": "Suspend a profile",
  // ---------- Data Privacy, Consent, Account Management & Retention (STEP 13) ----------
  "privacy:view": "View the Privacy Center",
  "privacy:manage": "Manage privacy settings",
  "privacy:consent:view": "View a profile's consent history",
  "privacy:consent:manage": "Manage a profile's consent records",
  "privacy:requests:view": "View privacy requests",
  "privacy:requests:manage": "Manage and resolve privacy requests",
  "privacy:export:view": "View data export requests",
  "privacy:export:create": "Create a data export on a profile's behalf",
  "privacy:delete:manage": "Approve or reject account deletion requests",
  "privacy:retention:view": "View retention policies",
  "privacy:retention:manage": "Configure retention policies",
  "privacy:hold:view": "View legal/administrative holds",
  "privacy:hold:manage": "Place or lift a legal/administrative hold",
  "privacy:incidents:view": "View privacy incidents",
  "privacy:incidents:manage": "Manage privacy incidents",
  "privacy:break-glass:manage": "Grant emergency break-glass access",
  "contact:reveal:override": "Share contact info outside an approved proposal",
  "sensitive:contact:view": "View private contact information (mobile, WhatsApp, email)",
  "sensitive:documents:view": "View private verification/identity documents",
  "sensitive:photos:view": "View profile photos",
  "privacy_incidents:view": "View privacy-incident cases",
  "privacy_incidents:review": "Review a privacy-incident case",
  "privacy_incidents:resolve": "Resolve a privacy-incident case",
  // ---------- Payment, Subscription, Packages & Financial Management (STEP 14) ----------
  "finance:view": "View the Finance Center",
  "finance:dashboard:view": "View the financial dashboard",
  "finance:payments:view": "View payments",
  "finance:payments:manage": "Manage payments and manual payment verification",
  "finance:invoices:view": "View invoices",
  "finance:invoices:manage": "Manage invoices",
  "finance:refunds:view": "View refunds",
  "finance:refunds:request": "Request a refund",
  "finance:refunds:approve": "Approve a refund",
  "finance:subscriptions:view": "View subscriptions",
  "finance:subscriptions:manage": "Manage subscriptions",
  "finance:packages:view": "View packages and pricing",
  "finance:packages:manage": "Manage packages, pricing, and entitlements",
  "finance:coupons:view": "View coupons and discounts",
  "finance:coupons:manage": "Manage coupons and discounts",
  "finance:reconciliation:view": "View financial reconciliation",
  "finance:reconciliation:manage": "Run financial reconciliation",
  "finance:reports:view": "View financial reports",
  "finance:reports:export": "Export a financial report",
  "sensitive:finance:view": "View sensitive financial details",
  "sensitive:finance:export": "Export sensitive financial data",

  // ---------- Payment Rollout Phases (STEP 14 add-on) ----------
  "finance:rollout:view": "View payment rollout stage, feature flags, and health",
  "finance:rollout:manage": "Change payment feature flags and beta/internal eligibility config",
  "finance:rollout:enable": "Advance the payment rollout stage forward",
  "finance:rollout:disable": "Disable payments (kill switch) or roll back the rollout stage",
  "finance:provider:manage": "Change the active payment provider or environment config",
  "finance:webhooks:view": "View payment webhook health and delivery status",
  // ---------- Production, DevOps & Recovery (STEP 15) ----------
  "system:view": "View System Health and operational status",
  "system:config:manage": "Change monitoring thresholds, backup policy and system configuration",
  "system:flags:manage": "Toggle feature flags",
  "system:maintenance:manage": "Enable/disable maintenance mode and change the operational state",
  "system:emergency:manage": "Use the emergency kill switches",
  "system:backup:view": "View backup and recovery status",
  "system:backup:trigger": "Trigger a backup or restore verification",
  "system:restore:approve": "Request or approve a restore",
  "system:jobs:view": "View background jobs and scheduled tasks",
  "system:jobs:manage": "Retry, cancel or resolve background jobs; run the scheduled tick",
  "alerts:view": "View alerts and incidents",
  "alerts:manage": "Acknowledge, assign, resolve alerts and open incidents",
  "readiness:view": "View Production Readiness and release records",
  "releases:manage": "Approve releases and record rollbacks",
  "ai:view": "View the AI Matchmaking Assistant and its overview",
  "ai:use": "Use AI analysis (profile summary, match explanation, comparison, data quality) on profiles you can access",
  "ai:copilot": "Use the Admin Copilot (read-only questions within your own permissions)",
  "ai:communication:draft": "Ask the AI to DRAFT messages (sending stays a separate, confirmed action)",
  "ai:report:use": "Ask the AI to summarise reports you are already allowed to see",
  "ai:config:manage": "Change AI settings (provider, limits, privacy, storage, prompts)",
  "ai:rollout:manage": "Change the AI rollout phase",
  "ai:killswitch": "Use the AI kill switch",
  "ai:activity:view": "View the AI activity log (metadata only)",
  "ai:usage:view": "View AI usage and estimated cost",
  "ai:test:run": "Run the AI safety/privacy/security/regression test suites",
  // ---------- Exact Admin Roles & Granular Permission Matrix (STEP 17) ----------
  "roles:view": "View roles and their permissions",
  "roles:create": "Create a custom role",
  "roles:edit": "Edit a role's permissions",
  "roles:disable": "Disable a role",
  "roles:assign": "Assign a role to an admin",
  "roles:delete": "Delete a custom role",

  // ---------- Workflow & Task Management (STEP 18) ----------
  "tasks:view": "View the Workflow & Tasks module",
  "tasks:view:own": "View your own assigned tasks (My Work Queue)",
  "tasks:view:team": "View your team's tasks (Team Work Queue)",
  "tasks:view:all": "View every task on the platform (Global Work)",
  "tasks:create": "Create a task automatically or manually",
  "tasks:create:manual": "Manually create a task via 'Create Task'",
  "tasks:assign": "Assign an unassigned task to a staff member",
  "tasks:assign:any": "Assign a task across any department/domain",
  "tasks:reassign": "Reassign an already-assigned task",
  "tasks:accept": "Accept a task assigned to you",
  "tasks:complete": "Mark a task complete",
  "tasks:reopen": "Reopen a completed/cancelled task",
  "tasks:cancel": "Cancel a task",
  "tasks:escalate": "Escalate a task to the next level",
  "tasks:escalate:senior": "Escalate a task to the senior/final tier",
  "tasks:comment": "Comment on a task",
  "tasks:comment:internal": "Post an internal-only task comment",
  "tasks:attachments:upload": "Upload an attachment to a task",
  "tasks:attachments:view": "View a task's attachments",
  "tasks:bulk-actions": "Perform bulk actions on multiple tasks at once",
  "tasks:templates:manage": "Create and edit task templates",
  "tasks:sla:manage": "Configure SLA targets per task type",
  "tasks:automation:manage": "Configure workflow automation rules",
  "tasks:workflow-failures:view": "View the Workflow Failures (dead-letter) queue",
  "tasks:workflow-failures:resolve": "Retry or resolve a failed workflow event",
  "tasks:reports:view": "View Workflow Reports and analytics",
  "staff:availability:manage": "Configure staff availability and backup routing",
  "approvals:view": "View approval requests",
  "approvals:create": "Create a high-risk action approval request",
  "approvals:submit": "Submit a draft approval request for review",
  "approvals:approve": "Approve an approval request",
  "approvals:reject": "Reject an approval request",
  "approvals:request-changes": "Request changes on an approval request",
  "approvals:assign": "Assign a checker to an approval request",
  "approvals:delegate": "Delegate approval decisions to another admin",
  "approvals:escalate": "Escalate an approval request",
  "approvals:cancel": "Cancel an approval request",
  "approvals:execute": "Execute an approved high-risk action",
  "approvals:audit:view": "View the approval audit trail",
  "approvals:policy:view": "View approval governance policies",
  "approvals:policy:manage": "Configure approval governance policies",
  "approvals:emergency-override": "Use the emergency override for a high-risk action",
  "approvals:bulk:view": "View bulk approval requests",
  "approvals:bulk:approve": "Approve a bulk sensitive action",
  "sensitive:approval:view": "View approval requests involving sensitive data",
  "sensitive:approval:approve": "Approve a sensitive-data approval request",
  "sensitive:approval:execute": "Execute a sensitive-data approval request",
  "finance:approval:view": "View financial approval requests",
  "finance:approval:approve": "Approve a financial approval request",
  "finance:approval:execute": "Execute an approved financial action",
  "privacy:approval:view": "View privacy approval requests",
  "privacy:approval:approve": "Approve a privacy approval request",
  "privacy:approval:execute": "Execute an approved privacy action",
  "security:approval:view": "View security approval requests",
  "security:approval:approve": "Approve a security approval request",
  "security:approval:execute": "Execute an approved security action",
  "ai:approval:view": "View AI governance approval requests",
  "ai:approval:approve": "Approve an AI governance approval request",
  "ai:approval:execute": "Execute an approved AI governance action",
  "search:view": "Search and browse candidates",
  "search:advanced": "Use the advanced smart filter builder",
  "search:sensitive": "Filter candidate search by sensitive fields (e.g. income)",
  "search:export": "Export candidate search results",
  "search:saved:view": "View saved search presets",
  "search:saved:create": "Save a new search preset",
  "search:saved:edit": "Edit a shared search preset",
  "search:saved:delete": "Delete a search preset",
  "search:bulk": "Perform bulk actions on search results",
  "candidate:view": "View candidate discovery results",
  "candidate:compare": "Compare multiple candidates side by side",
  "candidate:shortlist": "Create and manage candidate shortlists",
  "candidate:recommend": "Run mutual-compatibility candidate search",
  "family:manage": "Search, review, suspend, and manage family/guardian accounts",
  // ---------- STEP 23 — KYC, Duplicate Detection & Safety Intelligence ----------
  "risk:view": "View risk signals",
  "risk:review": "Review a risk signal",
  "risk:resolve": "Resolve a risk signal",
  "risk:escalate": "Escalate a risk signal",
  "risk:policy:view": "View risk policy settings",
  "risk:policy:manage": "Change risk policy settings",
  "duplicates:view": "View potential duplicate profiles",
  "duplicates:review": "Review a potential duplicate profile",
  "duplicates:resolve": "Confirm or dismiss a potential duplicate",
  "duplicates:link": "Link two profiles as a confirmed relationship",
  "duplicates:manage": "Trigger duplicate-detection scans",
  "relationships:view": "View account relationships",
  "relationships:create": "Manually record an account relationship",
  "relationships:review": "Review an account relationship",
  "relationships:manage": "Manage account relationships",
  "documents:download": "Download identity verification / general document original bytes",
  "verification:policy:view": "View verification policy settings",
  "verification:policy:manage": "Change verification policy settings",
  "safety:verification:restrict": "Restrict an account pending verification/safety review",
  "safety:verification:suspend": "Suspend an account for a verification/safety concern",
  "sensitive:verification:view": "View detailed identity verification data",
  "sensitive:risk:view": "View risk signal details",
  // ---------- STEP 23 Add-on — Legal Jurisdiction & Regulatory Compliance ----------
  "compliance:view": "View the compliance dashboard",
  "compliance:review": "Review a compliance rule, transfer, or incident",
  "compliance:manage": "Manage the compliance framework",
  "compliance:rules:view": "View legal/compliance rules",
  "compliance:rules:manage": "Create, edit, and change the status of compliance rules",
  "compliance:jurisdictions:view": "View configured jurisdictions",
  "compliance:jurisdictions:manage": "Create and edit jurisdictions",
  "compliance:providers:view": "View the third-party processor register",
  "compliance:providers:manage": "Manage third-party processors and their agreements",
  "compliance:requests:view": "View privacy/compliance requests",
  "compliance:requests:manage": "Manage privacy/compliance requests",
  "compliance:authority-requests:view": "View law enforcement / regulator requests",
  "compliance:authority-requests:manage": "Verify and respond to authority requests",
  "compliance:legal-holds:view": "View legal holds",
  "compliance:legal-holds:manage": "Place and request release of legal holds",
  "compliance:audit:view": "View the compliance audit trail",
  "ai:compliance:use": "Use the read-only AI compliance summary assistant",
  "sensitive:compliance:view": "View detailed compliance rule configuration",
  "sensitive:authority-request:view": "View authority request details and disclosed data",
  "sensitive:legal-hold:view": "View legal hold details",
  // ---------- STEP 24 — Fraud Prevention & Account Safety Intelligence ----------
  "risk:investigate": "Investigate risk cases and request further information",
  "risk:clear": "Clear a risk case after review",
  "risk:restrict": "Apply a temporary account restriction from a risk case (gated by approval)",
  "risk:suspend": "Suspend an account from a risk case (always gated by approval)",
  "risk:rules:view": "View risk rules and factors",
  "risk:rules:manage": "Change risk rules and factors (versioned, gated by approval)",
  "risk:configuration:view": "View risk thresholds and rate-limit configuration",
  "risk:configuration:manage": "Change risk thresholds and rate-limit configuration (gated by approval)",
  "risk:evidence:view": "View risk evidence records",
  "risk:evidence:manage": "Add risk evidence records",
  "risk:reports:view": "View risk and safety reports",
  "risk:reports:export": "Export risk and safety reports",
  "duplicates:merge": "Plan and request approval for a duplicate-account merge",
  "security:events:view": "View the security event ledger",
  "security:incidents:manage": "Manage emergency technical security controls and admin-security cases",
  "user-reports:view": "View applicant safety reports",
  "user-reports:manage": "Review and respond to applicant safety reports",
  "ai:risk:use": "Use the read-only AI risk-case summary assistant",
  "ai:crm:use": "Use the read-only AI CRM applicant/timeline summary assistant",
  "sensitive:security:view": "View admin-security investigations and privileged-access anomalies",
  "sensitive:device:view": "View device intelligence signals",
  "sensitive:network:view": "View network intelligence signals",
  "sensitive:evidence:view": "View sensitive evidence payloads",
  "communications:view": "View the communication center (queue, threads, history)",
  "communications:send": "Send a communication to an eligible recipient (policy-checked)",
  "communications:send_sensitive": "Send a communication that touches sensitive purposes (approval may apply)",
  "communications:bulk": "Create bulk communication (campaigns)",
  "communications:templates:view": "View communication templates and versions",
  "communications:templates:create": "Create communication templates",
  "communications:templates:edit": "Edit communication templates (creates a new version)",
  "communications:templates:approve": "Approve a submitted communication template",
  "communications:templates:activate": "Activate an approved communication template (gated by approval)",
  "communications:campaigns:view": "View communication campaigns",
  "communications:campaigns:create": "Create and edit communication campaigns",
  "communications:campaigns:approve": "Approve a communication campaign",
  "communications:campaigns:manage": "Start, pause and cancel communication campaigns",
  "communications:providers:view": "View communication providers and their health",
  "communications:providers:manage": "Configure communication providers (gated by approval)",
  "communications:webhooks:view": "View provider webhook events",
  "communications:logs:view": "View communication delivery logs",
  "communications:analytics:view": "View communication analytics",
  "communications:export": "Export communication analytics",
  "communications:suppress": "Add or lift communication suppressions (audited)",
  "sensitive:communication:view": "View sensitive communication content and manager-only comments",
  "sensitive:communication:send": "Send sensitive-purpose communications",
  "documents:view": "View documents and their metadata",
  "documents:upload": "Upload a document on behalf of a record (e.g. an administrative document)",
  "documents:edit": "Edit document metadata",
  "documents:review": "Review an uploaded document",
  "documents:verify": "Approve a document's verification status",
  "documents:reject": "Reject a document",
  "documents:share": "Share a document with another recipient (policy-checked)",
  "documents:revoke_share": "Revoke a document share",
  "documents:archive": "Archive a document",
  "documents:restore": "Restore an archived document",
  "documents:delete": "Delete a document (subject to retention/legal hold)",
  "documents:export": "Export document analytics or an approved document package",
  "documents:redact": "Create a redacted derivative of a document",
  "documents:manage_requests": "Create and manage document requests to applicants",
  "documents:manage_providers": "Configure document scan/OCR/signature providers",
  "documents:manage_retention": "Configure document retention policy",
  "documents:manage_legal_hold": "Place or lift a document legal hold",
  "documents:audit:view": "View the document access audit trail",
  "documents:sign": "Sign a document that has been sent to them for signature",
  "documents:sign:manage": "Create, void and manage document signature requests",
  "sensitive:documents:download": "Download a highly sensitive / restricted document",
  "sensitive:documents:share": "Share a highly sensitive / restricted document",
  "sensitive:documents:export": "Export a highly sensitive / restricted document",
  "sensitive:identity_documents:view": "View identity documents (passport, national ID and similar)",
  "verification:documents:review": "Review a document as part of identity verification",
  "verification:documents:approve": "Approve a document as part of identity verification",
  "verification:documents:reject": "Reject a document as part of identity verification",
  "verification:documents:reverify": "Mark a document as needing re-verification",

  // ---------- STEP 27 — Membership, Packages, Entitlements, Coupons & Referrals ----------
  "finance:entitlements:view": "View feature entitlement definitions and the entitlement matrix",
  "finance:entitlements:manage": "Edit package entitlements, the feature catalog, and grant/revoke entitlement overrides",
  "finance:credits:view": "View member service-credit balances and transactions",
  "finance:credits:manage": "Grant, refund, or adjust member service credits",
  "finance:pricing:view": "View pricing, package versions, and promotion configuration",
  "referrals:view": "View referral programs, codes, and referral records",
  "referrals:manage": "Create/edit referral programs and reward configuration",
  "referrals:review": "Resolve referrals flagged for fraud/eligibility review",
  "promotions:view": "View promotional campaigns",
  "promotions:manage": "Create/edit/activate promotional campaigns",

  // ---------- STEP 28 — CRM, Applicant Lifecycle & Lead Management ----------
  "crm:view": "View CRM records (pipeline, table, and detail views)",
  "crm:create": "Create a CRM record",
  "crm:edit": "Edit a CRM record's fields",
  "crm:archive": "Archive a CRM record",
  "crm:restore": "Restore an archived CRM record",
  "crm:assign": "Assign a CRM record or lead to staff",
  "crm:reassign": "Reassign a CRM record or lead to different staff",
  "crm:lifecycle:view": "View a CRM record's lifecycle stage and history",
  "crm:lifecycle:manage": "Transition a CRM record's lifecycle stage",
  "crm:leads:view": "View leads",
  "crm:leads:manage": "Create/edit leads and lead intake",
  "crm:leads:convert": "Convert a qualified lead into an applicant account and CRM record",
  "crm:notes:view": "View CRM notes visible to your role",
  "crm:notes:create": "Add a CRM note",
  "crm:notes:edit": "Edit a CRM note",
  "crm:notes:delete": "Soft-delete a CRM note",
  "crm:notes:manager_view": "View manager-only CRM notes",
  "crm:followups:view": "View CRM follow-ups",
  "crm:followups:create": "Create a CRM follow-up",
  "crm:followups:edit": "Edit a CRM follow-up",
  "crm:followups:complete": "Mark a CRM follow-up complete or reopen it",
  "crm:tags:view": "View CRM tags",
  "crm:tags:manage": "Create/edit CRM tags and apply/remove them on records",
  "crm:search": "Search CRM records with filters",
  "crm:saved_views:view": "View saved CRM views shared with you",
  "crm:saved_views:create": "Create a saved CRM view",
  "crm:saved_views:edit": "Edit a saved CRM view",
  "crm:saved_views:delete": "Delete a saved CRM view",
  "crm:analytics:view": "View CRM analytics",
  "crm:reports:view": "View CRM reports",
  "crm:export": "Export CRM data (subject to field-level security)",
  "crm:bulk": "Run bulk CRM actions (assign/tag/follow-up/priority/archive)",
  "crm:merge:view": "View a duplicate-CRM-record merge plan",
  "crm:merge:request": "Request a duplicate-CRM-record merge",
  "crm:merge:approve": "Approve and execute a duplicate-CRM-record merge",
  "crm:workflow:view": "View CRM automation workflow rules",
  "crm:workflow:manage": "Create/edit CRM automation workflow rules",
  "crm:sla:view": "View CRM/follow-up SLA status",
  "crm:sla:manage": "Configure CRM/follow-up SLA and reminder policies",
  "crm:audit:view": "View the CRM audit trail",
  "sensitive:crm:view": "View sensitive fields surfaced inside a CRM record",
  "sensitive:crm:export": "Export sensitive CRM fields",
  "sensitive:crm:notes:view": "View internal/manager-only CRM notes regardless of role default",
  "sensitive:crm:communication:view": "View linked communication history inside a CRM record",
  "sensitive:crm:documents:view": "View linked document metadata inside a CRM record",
  "sensitive:crm:risk:view": "View the neutral risk indicator inside a CRM record",
};

function moduleAndAction(key: Permission): { module: string; action: string } {
  const parts = key.split(":");
  return { module: parts[0], action: parts.slice(1).join(":") };
}

export async function ensurePermissionDefsSeeded(): Promise<void> {
  const keys = Object.keys(DESCRIPTIONS) as Permission[];
  await prisma.$transaction(
    keys.map((key) => {
      const { module, action } = moduleAndAction(key);
      return prisma.permissionDef.upsert({
        where: { key },
        update: { module, action, description: DESCRIPTIONS[key] ?? null },
        create: { key, module, action, description: DESCRIPTIONS[key] ?? null },
      });
    })
  );
}
