// Operational runbooks (spec §55). Single source of truth: rendered by
// Admin → Operations → Runbooks and mirrored in docs/RUNBOOKS.md. Each one is
// written against features that actually exist in this system. Steps that are
// manual (Vercel / Neon / GitHub consoles) are labelled as such — the app does
// not pretend to automate them.

export interface Runbook {
  id: string;
  title: string;
  summary: string;
  detection: string[];
  checks: string[];
  authorizedActions: string[];
  verification: string[];
  recovery: string[];
  audit: string[];
}

export const RUNBOOKS: Runbook[] = [
  {
    id: "deployment",
    title: "Deployment",
    summary: "Ship a change to staging, then production, with verification at every step.",
    detection: ["A new commit merged to the production branch triggers a Vercel deployment.", "The release is auto-registered (LPP-REL-######) the first time an instance of the new build starts."],
    checks: ["CI green for the commit: typecheck, lint, tests, security scan, dependency audit, build, migration validation.", "Production Readiness shows no NEW blocking gates.", "A verified backup exists from the last 24 h (System Health → Backup & Recovery).", "Migrations are backward-compatible (expand → migrate → contract); no destructive migration without written approval."],
    authorizedActions: ["Merge to the protected production branch (needs GitHub branch-protection approval — manual setting).", "SUPER_ADMIN approves the release in Production Readiness → Releases (password re-confirmation)."],
    verification: ["Release status becomes HEALTHY (database + configuration verified automatically).", "deploy-gate workflow posts SMOKE and SECURITY_SMOKE evidence for the deployed commit.", "System Health overview shows no new errors for 15 minutes."],
    recovery: ["If the release is UNHEALTHY or smoke tests fail: stop further deployments and follow the Rollback runbook."],
    audit: ["DEPLOYMENT_STARTED / DEPLOYMENT_COMPLETED / DEPLOYMENT_FAILED are written automatically; approval is audited with the approver."],
  },
  {
    id: "rollback",
    title: "Rollback",
    summary: "Return to the previous stable release without corrupting data.",
    detection: ["Release marked UNHEALTHY, or error-rate / latency alerts fire shortly after a deployment.", "Post-deploy smoke tests fail."],
    checks: ["Production Readiness → Releases → the release's Rollback assessment: SAFE / REQUIRES_REVIEW / UNKNOWN.", "REQUIRES_REVIEW means migrations were applied after the target release. Prisma migrations are forward-only — confirm the older code tolerates the newer schema, or restore from a verified backup instead."],
    authorizedActions: ["SUPER_ADMIN only. In Vercel: promote the previous deployment (manual). Then record the rollback in Production Readiness (password re-confirmation + reason)."],
    verification: ["Health endpoints green; System Health shows the previous version; no new critical alerts.", "Run data-integrity checks (System Health → Backup & Recovery → Post-restore validation)."],
    recovery: ["If schema and code are incompatible and the assessment is REQUIRES_REVIEW, switch to the Backup restoration runbook rather than forcing the rollback."],
    audit: ["ROLLBACK_STARTED and ROLLBACK_COMPLETED with actor, reason and release code."],
  },
  {
    id: "backup",
    title: "Backup",
    summary: "Create, verify and retain encrypted backups.",
    detection: ["Backup failed / stale alerts; last successful backup older than the configured limit."],
    checks: ["BACKUP_ENCRYPTION_KEY is configured (never reuse NEXTAUTH_SECRET).", "Backup Policy is enabled and retention counts are what the deployment's legal/operational rules require.", "Optional but recommended: BACKUP_BLOB_READ_WRITE_TOKEN points to a SEPARATE storage account."],
    authorizedActions: ["Trigger a manual database or file backup (permission system:backup:trigger).", "Scheduled backups run in the daily tick and verify themselves (decrypt → parse → manifest)."],
    verification: ["Backup shows COMPLETED with verification PASSED.", "File mirror shows every private file copied."],
    recovery: ["A failed run explains why. 'Exceeded time/size budget' means the database outgrew the in-app backup: use Neon point-in-time recovery (primary) and the optional pg_dump GitHub workflow."],
    audit: ["BACKUP_TRIGGERED and BACKUP_VERIFIED. Backup contents and storage URLs are never shown in any admin interface."],
  },
  {
    id: "restore",
    title: "Backup restoration",
    summary: "Restore data from a verified backup safely. The application never overwrites live data by itself.",
    detection: ["Data loss, corruption, failed migration, or security incident requiring recovery."],
    checks: ["Pick a backup with verification PASSED. Confirm the target: a scratch database first, production only if unavoidable.", "Freeze writes: set the operational state to MAINTENANCE / RECOVERY."],
    authorizedActions: ["Request a restore (system:restore:approve + password re-confirmation + typing the exact phrase 'RESTORE <backup code>').", "A DIFFERENT SUPER_ADMIN approves. An operator then runs scripts/restore-backup.ts with the approved request and the backup key (out of app).", "Mark the request executed."],
    verification: ["Run 'Post-restore validation' (connectivity, core data sets, integrity checks).", "Log in as an admin, verify permissions, profiles, proposals, payments, audit logs and file access."],
    recovery: ["If validation fails, keep MAINTENANCE on, restore into a scratch database and compare before touching production again."],
    audit: ["RESTORE_REQUESTED, RESTORE_TRIGGERED (approve / reject / executed / cancel) and the post-restore integrity run."],
  },
  {
    id: "payment-outage",
    title: "Payment outage",
    summary: "Payments failing or the provider is unavailable.",
    detection: ["Payment-failure-spike or provider alerts; failed-payments count in System Health → Payments."],
    checks: ["Provider health and environment safety (Finance Center → System Health).", "Recent webhook failures and reconciliation mismatches."],
    authorizedActions: ["SUPER_ADMIN: Finance Center → Rollout → Disable Payments, or the emergency payments switch (System Configuration → Emergency). Both only block NEW checkouts; existing subscriptions, invoices and refunds are untouched."],
    verification: ["Applicants see the neutral 'Online payments are temporarily unavailable' message; no new orders are created."],
    recovery: ["Fix the provider/credentials, run reconciliation, then re-enable through the rollout stages (never skipping stages)."],
    audit: ["PAYMENT_KILL_SWITCH_USED / EMERGENCY_SWITCH_CHANGED with reason."],
  },
  {
    id: "webhook-outage",
    title: "Webhook outage",
    summary: "Provider webhooks are failing, delayed or being spoofed.",
    detection: ["Webhook failure spike alert; webhook signature counter rising in System Health → Security."],
    checks: ["Failed events and stuck RECEIVED events (integrity checks).", "Is STRIPE_WEBHOOK_SECRET current? Is the endpoint URL correct for this environment?"],
    authorizedActions: ["Finance Center → Rollout → toggle 'Provider webhook processing' (intake pauses, provider retries later).", "Run reconciliation to detect payments the provider settled that we missed."],
    verification: ["A test event is processed; failed count stops rising."],
    recovery: ["Replay missed events from the provider dashboard; duplicates are ignored (idempotency key)."],
    audit: ["PAYMENT_FEATURE_FLAG_CHANGED; reconciliation run and any incident case."],
  },
  {
    id: "database-outage",
    title: "Database outage",
    summary: "The database is unreachable or extremely slow.",
    detection: ["/api/health/ready returns 503; DATABASE_OUTAGE alert (CRITICAL, auto-opens an incident)."],
    checks: ["Neon status page and project dashboard (manual).", "Connection string / pooler settings changed recently? Connection limit reached?"],
    authorizedActions: ["Set the operational state to DEGRADED/MAINTENANCE if the admin console is still reachable (it may not be). Otherwise use Vercel to redeploy or Neon to restore a branch/point-in-time (manual)."],
    verification: ["Ready endpoint 200; System Health database latency normal; run integrity checks."],
    recovery: ["If data is damaged: Backup restoration runbook. Prefer Neon point-in-time recovery for near-zero data loss."],
    audit: ["Incident case (LPP-INC) with timeline; state changes are audited."],
  },
  {
    id: "storage-outage",
    title: "Storage outage",
    summary: "Photo/document/evidence storage is failing.",
    detection: ["Storage-failure alerts; storage error counter in System Health → Storage."],
    checks: ["Vercel Blob status (manual); token still valid; account quota."],
    authorizedActions: ["Emergency uploads switch (System Configuration → Emergency) to stop new uploads while reads keep failing gracefully."],
    verification: ["Uploads succeed; existing files stream through their authenticated routes."],
    recovery: ["Restore missing objects from the file mirror (ciphertext copies in the backup store) — objects are byte-identical, so they decrypt with the original keys."],
    audit: ["EMERGENCY_SWITCH_CHANGED; incident case."],
  },
  {
    id: "notification-outage",
    title: "Notification outage",
    summary: "Email/SMS/WhatsApp delivery is failing.",
    detection: ["Failed deliveries by channel in System Health → Communications; queue backlog alert."],
    checks: ["Provider credentials and quotas. NOTE: until a real provider is configured, messages (including admin OTP codes) are only written to the server log."],
    authorizedActions: ["Turn off the affected channel with the notifications / whatsapp feature flag; failed rows are kept and retried automatically (bounded) when re-enabled."],
    verification: ["Test send succeeds; failed count returns to zero."],
    recovery: ["Use Communication Center → Retry for individual messages; the daily job retries the last 24 h within the retry limit."],
    audit: ["FEATURE_FLAG_CHANGED; NOTIFICATION_RETRY_TRIGGERED."],
  },
  {
    id: "account-security-incident",
    title: "Account / security incident",
    summary: "Suspected admin account compromise, data exposure or attack.",
    detection: ["Failed-login spike, permission-violation spike, unexpected admin activity, security flags."],
    checks: ["Audit Log (filter by actor, action, correlation ID); Active Sessions; login history."],
    authorizedActions: ["Revoke sessions and deactivate the account (Admin Users).", "Rotate secrets (NEXTAUTH_SECRET invalidates ALL sessions and stored files — read the rotation warning first).", "Emergency switches for public access if exposure is ongoing.", "Open a SECURITY incident case; preserve evidence."],
    verification: ["No further suspicious activity; alert resolved with a written resolution."],
    recovery: ["Follow legal/regulatory notification obligations for the deployment (not encoded in the app)."],
    audit: ["Everything above is audited; incident case records the timeline."],
  },
  {
    id: "maintenance-mode",
    title: "Maintenance mode",
    summary: "Take the public site offline cleanly for planned work.",
    detection: ["Planned change window."],
    checks: ["No payment in flight that would be confused (payments finish; webhooks keep processing).", "Announce the window; choose ON or SCHEDULED."],
    authorizedActions: ["System Configuration → Maintenance: set mode, optional window and message (password re-confirmation + reason)."],
    verification: ["Public pages show the neutral maintenance page; admin console, webhooks, cron and health endpoints stay reachable."],
    recovery: ["Set mode OFF. If the site does not return, check /api/system-state and the operational state (must be NORMAL)."],
    audit: ["MAINTENANCE_ENABLED / MAINTENANCE_DISABLED with previous and new values."],
  },
  {
    id: "emergency-shutdown",
    title: "Emergency shutdown",
    summary: "Last resort: stop parts of the system fast. Not a substitute for normal operational controls.",
    detection: ["Active attack, data exposure, runaway abuse, or a defect corrupting data."],
    checks: ["Can a narrower control solve it? (feature flag, single emergency switch, payment kill switch). Prefer those."],
    authorizedActions: ["SUPER_ADMIN: System Configuration → Emergency — payments, registrations, profile submissions, matching, proposals, notifications, uploads, or public access; or set the operational state to EMERGENCY (closes everything public at once). Password re-confirmation and a written reason are mandatory."],
    verification: ["Affected features return the neutral 503 message; admin console and webhooks stay available."],
    recovery: ["Investigate and fix, then re-open switches one at a time; set the state back to NORMAL; close the incident only after validation."],
    audit: ["EMERGENCY_SWITCH_CHANGED / OPERATIONAL_STATE_CHANGED with actor, previous value, new value, reason."],
  },
  // ---- STEP 16 — AI Assistant --------------------------------------------------
  {
    id: "ai-provider-outage",
    title: "AI provider outage / integration failure",
    summary: "The external AI provider (if enabled) is failing. Deterministic matching and every other feature keep working; the assistant falls back to the built-in analysis.",
    detection: ["Alert AI_FAILURE_RATE; Admin → AI Assistant → AI Health shows a failing provider; admins see 'AI assistance temporarily unavailable'."],
    checks: ["AI Health: failure rate, last successful request, provider error codes (never raw provider messages).", "Is ANTHROPIC_API_KEY valid and the provider status page healthy? (manual — provider console)."],
    authorizedActions: ["SUPER_ADMIN: AI Settings → set the provider to the built-in rules provider, or use the AI kill switch if the failure is noisy.", "Do not retry manually in a loop; requests are already retried within limits."],
    verification: ["AI Health shows requests succeeding again; a test summary works."],
    recovery: ["Re-enable the external provider only after the provider is healthy and the AI test suite passes."],
    audit: ["AI_PROVIDER_ERROR, AI_CONFIGURATION_CHANGED, AI_KILL_SWITCH_USED with actor and reason."],
  },
  {
    id: "ai-privacy-incident",
    title: "AI privacy incident (data leakage / unauthorized access / unsafe output)",
    summary: "AI output contained, or a request attempted to obtain, data the requester may not see; or the safety filter is blocking repeatedly.",
    detection: ["Alerts AI_UNAUTHORIZED_ACCESS or AI_UNSAFE_OUTPUT; AI_SAFETY_BLOCK / AI_DATA_ACCESS_DENIED audit events; a member or admin report."],
    checks: ["AI Activity: who, which feature, which rule fired (metadata only — text is never stored).", "Was an external provider used? (AI History → provider, consent outcome).", "Any prompt-injection text in a profile? (safety events)."],
    authorizedActions: ["SUPER_ADMIN: use the AI kill switch immediately if data may have left the system.", "Open a Privacy Incident case (Case Management) and follow the privacy incident process; notification of members is a legal decision this system does not make."],
    verification: ["Kill switch active; AI requests return 'not currently available'; audit shows AI_KILL_SWITCH_USED."],
    recovery: ["Fix the cause, run the AI safety/privacy/security suites to a pass, then re-enable through the rollout phases."],
    audit: ["AI_SAFETY_BLOCK, AI_DATA_ACCESS_DENIED, AI_KILL_SWITCH_USED, CASE_CREATED."],
  },
  {
    id: "ai-kill-switch",
    title: "AI kill switch",
    summary: "Stops every AI request instantly without touching matching, proposals, payments or any other workflow.",
    detection: ["Suspected unsafe output, privacy exposure, runaway cost, or provider abuse."],
    checks: ["Confirm the problem is AI-related (AI Health / AI Activity)."],
    authorizedActions: ["SUPER_ADMIN: Admin → AI Assistant → AI Settings → Kill switch → Disable AI assistance (reason required). Re-enabling requires password re-confirmation."],
    verification: ["AI endpoints return 'AI assistance is temporarily unavailable'; existing AI history stays protected; deterministic matching unaffected."],
    recovery: ["Deactivate the kill switch only after the cause is understood; the rollout phase is preserved."],
    audit: ["AI_KILL_SWITCH_USED with actor, previous state and reason."],
  },
];
